### ISSUE TITLE
complete.js doesn't offer snippets hooked up to ace via addSnippet

### ISSUE THREAD

**Issue by Pike** [c9/c9.ide.language#3]
For c9sdk bundles, complete.js now offers an API to hook a snippet into ace' snippetManager, but there doesn't seem to be a code path to hook them from the snippetManager to the popup.

**Comment by Pike** [comment]
I've glanced at this, but couldn't find the right point to hook into complete.js. A pointer would be great.

**Comment by nightwing** [comment]
This was caused by snippet completer and ace snippet manager using different ids for modes loaded from plugins. Should be fixed with https://github.com/c9/c9.ide.language.generic/commit/7505e7902eeda4e5974224514271a3fd1b1514d9

**Comment by Pike** [comment]
Yes, thanks.
