### ISSUE TITLE
Bug in worker

### ISSUE THREAD

**Issue by ghost** [c9/c9.ide.language#4]
I believe this line should read `var t = startTime` as startTime is not a function - we're using this fix in our build and I believe upstream could benefit, as its critical if a languageHandler uses onUpdate().

https://github.com/c9/c9.ide.language/blob/master/worker.js#L1152

**Comment by romanman** [comment]
@nightwing : amigo, what do you think about that one ?

**Comment by lennartcl** [comment]
Thanks for reporting guys! We'll fix this in upstream.
